Improve mint-related scripts to work with Plutus policies

diff --git a/scripts/policyid b/scripts/policyid
--- a/scripts/policyid
+++ b/scripts/policyid
@@ -1,9 +1,40 @@
 #!/usr/bin/env bash
 
-if [ -z "$1" ]; then
-    >&2 echo "expected policy name as argument"
-    exit 1
+while getopts ":n:p:" opt; do
+  case $opt in
+    n)
+      if [ -z "${OPTARG}" ]; then
+        >&2 echo "error: missing script name argument"
+        exit 1
+      fi
+      scripts_path=$NATIVE_SCRIPTS_PATH
+      script_name=$OPTARG
+      file_ext="script"
+      ;;
+    p)
+      if [ -z "${OPTARG}" ]; then
+        >&2 echo "error: missing script name argument"
+        exit 1
+      fi
+      scripts_path="$PLUTUS_SCRIPTS_PATH"
+      script_name=$OPTARG
+      file_ext="plutus"
+      ;;
+    \?)
+      >&2 echo "Usage: policyid [-n FILENAME] [-p FILENAME]"
+      exit 1
+      ;;
+    :)
+      >&2 echo "option -$OPTARG requires an argument"
+      exit 1
+      ;;
+  esac
+done
+
+if [ -z "$script_name" ]; then
+  >&2 echo "Usage: policyid [-n FILENAME] [-p FILENAME]"
+  exit 1
 fi
 
 cardano-cli transaction policyid \
---script-file $NATIVE_SCRIPTS_PATH/$1.script
+--script-file $scripts_path/$script_name.$file_ext
diff --git a/scripts/token b/scripts/token
--- a/scripts/token
+++ b/scripts/token
@@ -1,13 +1,45 @@
 #!/usr/bin/env bash
 
-if [ -z "$1" ]; then
-    >&2 echo "expected policy name as argument"
+function usage {
+    echo "Usage: $0 [-n|-p] POLICY_NAME TOKEN_NAME"
+    echo "  -n: Native script"
+    echo "  -p: Plutus script"
+    exit 1
+}
+
+# Check for the number of arguments
+if [ $# -ne 3 ]; then
+    usage
+fi
+
+# Parse command-line options
+while getopts ":np" opt; do
+    case $opt in
+        n)
+            script_type="n"
+            ;;
+        p)
+            script_type="p"
+            ;;
+        \?)
+            echo "Invalid option: -$OPTARG"
+            usage
+            ;;
+    esac
+done
+
+# Shift the parsed options out of the argument list
+shift $((OPTIND - 1))
+# Assign arguments
+policy_name="$1"
+token_name="$2"
+
+policy_id=$(policyid "-$script_type" "$policy_name" 2>&1)
+
+# Continue only if policyid script succeeded:
+if [ $? -ne 0 ]; then
+    echo "$policy_id"
     exit 1
 fi
 
-if [ -z "$2" ]; then
-    >&2 echo "expected token name as argument"
-    exit 1
-fi
-
-echo -n $(policyid $1).$(token-name $2)
+echo -n $policy_id.$(token-name $token_name)
